patreon: teamarcades
open_collective: # Replace with a single Open Collective username
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
custom:
  [
    'https://6889.fun/',
    'https://teamarcades.xyz/',
  ]
